# Generated by Django 3.2.24 on 2024-02-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20240211_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
