# Generated by Django 3.2.24 on 2024-02-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_property_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyfiles',
            old_name='image',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='propertyfiles',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='listings.property'),
        ),
    ]
