# Generated by Django 3.2.24 on 2024-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20240211_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
